package com.zzl.common.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;

/**
 * @author: 张志龙
 * @Date: 2018/8/19 22:22
 * @Description:
 */

@AllArgsConstructor
public enum OperationTypeEnum{
                              INDEX_MENU("查询首页菜单"),
                              TO_INDEX("打开首页"),
                              TURN_COURSEWARE_FILE("打开理论课件附件上传页面"),
                              TURN_TAPE_FILE("打开录音附件上传页面"),
                              UPLOAD_COURSEWARE_FILE("上传理论课件附件"),
                              UPLOAD_TAPE_FILE("上传英语录音附件"),
                              DOWNLOAD_FILE("下载附件"),
                              TURN_SELECT_ORGS("打开下载导入用户模板页面"),
                              DOWNLOAD_USER_TEMPLATE("下载用户导入模板"),
                              IMPORT_USER_INFO("导入用户"),
                              TURN_INIT_STUDY_PLAN("打开培训计划页面"),
                              GENERATE_STUDY_PLAN("重新生成培训计划"),
                              GENERATE_USER_STUDY_PLAN("重新生成个人培训计划"),
                              TURN_LOGIN_LOG("打开登录日志页面"),
                              GET_LOGIN_LOG_DATA("查询登录日志数据"),
                              TURN_MODIFY_PASSWORD("打开密码修改页面"),
                              MODIFY_PASSWORD("确认修改密码"),
                              LOAD_USER_PIC("加载用户头像"),
                              EDITOR_BOOK("编辑教材名称"),
                              GET_BOOK_TABLE_DATA("获取教材名称表格数据"),
                              OPEN_BOOK_MANAGEMENT_PAGE("打开教材名称管理页面"),
                              GET_COURSEWARE_MANAGEMENT_TABLE_HEAD("获取课件管理表格表头"),
                              GET_COURSEWARE_MANAGEMENT_TABLE_DATA("获取课件管理表格数据"),
                              GET_COURSEWARE_COMBOBOX_DATA("获取课件下拉框值"),
                              OPEN_COURSEWARE_GENERAL("启用通用课件"),
                              CLOSE_COURSEWARE_GENERAL("关闭通用课件"),
                              DELETE_COURSEWARE_GENERAL("删除通用课件"),
                              OPEN_COURSEWARE_EXTENSION("启用扩展课件"),
                              CLOSE_COURSEWARE_EXTENSION("关闭扩展课件"),
                              DELETE_COURSEWARE_EXTENSION("删除闭扩展课件"),
                              ADD_COURSEWARE_BUTTON_SHOW("获取新增课件按钮显示隐藏状态"),
                              GET_COURSEWARE_SOLE_ID("获取课件唯一ID值"),
                              GET_COURSEWARE_SORT_DATA("获取课件排序初始化数据"),
                              SAVE_UPDATE_COURSEWARE_SORT_DATA("保存修改课件排序数据"),
                              OPEN_COURSEWARE_SORT_PAGE("打开课件排序页面"),
                              OPEN_COURSEWARE_COURSEWARE_PAGE("打开课件管理页面"),
                              EDITOR_ENGLISH_COURSEWARE("编辑英语课件"),
                              GET_UPDATE_ENGLISH_COURSEWARE("获取修改英语课件初始化数据"),
                              GET_ENGLISH_COURSEWARE_TAPE_TABLE_HEAD("获取新增英语课件英语录音表格表头"),
                              GET_ENGLISH_COURSEWARE_TAPE_TABLE_DATA("获取新增英语课件英语录音表格数据"),
                              OPEN_SAVE_ENGLISH_COURSEWARE_PAGE("打开新增英语课件页面"),
                              OPEN_UPDATE_ENGLISH_COURSEWARE_VIEW("打开修改英语课件页面"),
                              OPEN_VIEW_ENGLISH_COURSEWARE_VIEW("打开查看英语课件页面"),
                              GET_TAPE_TABLE_HEAD("获取英语录音表格表头"),
                              GET_TAPE_TABLE_DATA("获取英语录音表格数据"),
                              EDITOR_ENGLISH_TAPE("编辑英语录音"),
                              OPEN_ENGLISH_TAPE_MANAGEMENT("打开英语录音管理页面"),
                              OPEN_SAVE_ENGLISH_TAPE("打开新增英语录音页面"),
                              OPEN_UPDATE_ENGLISH_TAPE("打开修改英语录音页面"),
                              OPEN_CHOOSE_ENGLISH_TAPE("打开选择英语录音页面"),
                              EDITOR_THEORY_COURSEWARE("编辑理论课件"),
                              GET_UPDATE_THEORY_COURSEWARE_DATA("获取修改理论课件初始化数据"),
                              OPEN_SAVE_THEORY_COURSEWARE("打开新增理论课件页面"),
                              OPEN_UPDATE_THEORY_COURSEWARE("打开修改理论课件页面"),
                              OPEN_VIEW_THEORY_COURSEWARE("打开查看理论课件页面"),
                              GET_USER_MANAGEMENT_OPEN_TABLE_DATA("获取表格数据(开启)"),
                              GET_USER_MANAGEMENT_STOP_TABLE_DATA("获取表格数据(关闭)"),
                              STOP_USER("停用用户"),
                              OPEN_USER("启用用户"),
                              EQP_USER("设备重置"),
                              GET_USER_COMBOBOX_DATA("获取用户下拉框值"),
                              SAVE_USER("保存新增用户"),
                              UPDATE_USER("保存修改用户"),
                              GET_USER_TREE_DATA("获取用户下拉树数据"),
                              SAVE_ROLE("保存角色"),
                              GET_ALL_ROLE_DATA("获取所有角色数据"),
                              SAVE_ROLE_OPERATION("保存角色与操作权限关系"),
                              SAVE_ROLE_MENU("保存角色与菜单关系"),
                              ADD_SAVE_ORGANIZATION("新增保存组织机构"),
                              UPDATE_SAVE_ORGANIZATION("修改保存组织机构"),
                              DELETE_ORGANIZATION("删除组织机构"),
                              OPEN_USER_MANAGEMENT_VIEW("打开用户管理页面(启用)"),
                              OPEN_USER_MANAGEMENT_STOP_VIEW("打开用户管理页面(停用)"),
                              OPEN_SAVE_USER_VIEW("打开用户新增页面"),
                              OPEN_UPDATE_USER_VIEW("打开用户修改页面"),
                              OPEN_USER_VIEW("打开用户查看页面"),
                              OPEN_USER_ROLE("打开用户角色设置页面"),
                              OPEN_ROLE_OPERATION("打开设置角色操作权限页面"),
                              OPEN_CHECKBOX_OPERATION("多选操作权限页面"),
                              OPEN_ROLE_MENU("打开设置角色菜单页面"),
                              OPEN_CHECKBOX_MENU("打开多选菜单权限页面"),
                              OPEN_ORGANIZATION_MAINTAIN("打开维护组织结构页面"),
                              OPEN_ADD_ORGANIZATION("打开新增组织结构页面"),
                              OPEN_UPDATE_ORGANIZATION("打开修改组织结构页面"),
                              GET_HEAD_PORTRAIT_BY_USER_ID("根据用户ID获取用户头像图片"),
                              OPEN_TAPE_SORT_VIEW("打开英语录音排序页面"),
                              GET_TAPE_SORT_DATA("获取英语录音排序初始化数据"),
                              SAVE_UPDATE_ENGLISH_TAPE_SORT_DATA("保存修改英语录音排序数据"),
                              TO_OPERATION_LOG("跳转操作日志管理"),
                              GET_OPERATION_LOG_TABLE_DATA("获取操作日志表格数据"),
                              TO_HISTORY_THEORY_COURSEWARE("跳转查看历史理论课件页面"),
                              GET_HISTORY_THEORY_COURSEWARE_DATA("获取历史理论课件数据"),
                              TO_HISTORY_ENGLISH_COURSEWARE("跳转查看历史英语课件页面"),
                              GET_HISTORY_ENGLISH_COURSEWARE_DATA("获取历史英语课件数据"),
                              TO_HISTORY_ENGLISH_TAPE("跳转查看历史英语录音页面"),
                              GET_HISTORY_ENGLISH_TAPE_DATA("获取历史英语录音数据"),
                              TO_HISTORY_BOOK("跳转查看历史教材名称页面"),
                              GET_HISTORY_BOOK("获取历史教材名称数据"),
                              TO_HISTORY_USER("跳转查看历史用户页面"),
                              GET_HISTORY_USER_DATA("获取历史用户数据"),
                              RESET_USER_PASSWORD("重置用户密码"),
                              TO_COUNT_REPORT("跳转统计报表页面"),
                              GET_COUNT_REPORT_TABLE_DATA("获取统计报表表格数据"),
                              GET_COUNT_REPORT_COMBOBOX_DATA("获取统计报表下拉框值"),
                              COUNT_REPORT_EXPORT("统计报表导出"),
                              GET_MANAGE_OPEN_AREA_TREE_DATA("获取管理开发大区数据"),
                              SAVE_MANAGE_OPEN_AREA_TREE_DATA("保存管理开发大区数据"),
                              TO_MANAGE_OPEN_AREA("跳转管理开放大区页面"),
                              UNLOCK_USER("解锁用户"),
                              REFRESH_SESSION("刷新组织信息")
                              ;
                            

    @Getter
    @Setter
    private String operationTypeExplain;

}
